/**
 * Cross-cutting domain primitives.
 *
 * These now live in `@agrisense/shared`, so the PWA validates against the same
 * locale list, the same coordinate bounds and the same district and crop
 * enums the API enforces. This module stays as the API's way in to them:
 * every existing `@shared/types` and `@shared` import keeps working, and
 * server-only additions still have somewhere to go.
 */
export {
  ACTIVITY_TYPES,
  CALENDAR_PAGE_SIZE_DEFAULT,
  CALENDAR_PAGE_SIZE_MAX,
  CALENDAR_UPCOMING_DAYS_DEFAULT,
  CALENDAR_UPCOMING_DAYS_MAX,
  ISO_DATE_PATTERN,
  SRI_LANKA_UTC_OFFSET_MINUTES,
  TASK_SOURCES,
  UUID_V4_PATTERN,
  activityTypeSchema,
  addDays,
  calendarListQuerySchema,
  calendarTaskCompleteSchema,
  calendarTaskCreateSchema,
  calendarTaskIdSchema,
  calendarTaskSchema,
  calendarTaskUpdateSchema,
  calendarUpcomingQuerySchema,
  isActivityType,
  isIsoDate,
  isUuidV4,
  isoDateSchema,
  taskSourceSchema,
  toIsoDate,
  todayInSriLanka,
  uuidV4Schema,
  CROP_CODES,
  DEFAULT_LOCALE,
  DISTRICTS,
  LOCALES,
  PLOT_PAGE_SIZE_DEFAULT,
  PLOT_PAGE_SIZE_MAX,
  cropCodeSchema,
  districtSchema,
  farmerProfileSchema,
  farmerProfileUpdateSchema,
  geoLinearRingSchema,
  geoPointSchema,
  geoPolygonSchema,
  geoPositionSchema,
  isCropCode,
  isDistrict,
  isLocaleCode,
  localeCodeSchema,
  localeSchema,
  plotCreateSchema,
  plotIdSchema,
  plotListQuerySchema,
  plotSchema,
  plotUpdateSchema,
  point,
  polygonCentroid,
  type ActivityType,
  type CalendarListQuery,
  type CalendarTaskCompleteInput,
  type CalendarTaskId,
  type CalendarTaskInput,
  type CalendarTaskRecord,
  type CalendarTaskUpdateInput,
  type CalendarUpcomingQuery,
  type IsoDate,
  type TaskSource,
  type CropCode,
  type District,
  type FarmerProfileInput,
  type FarmerProfileUpdateInput,
  type GeoLinearRing,
  type GeoPoint,
  type GeoPolygon,
  type GeoPosition,
  type Locale,
  type LocaleCode,
  type PlotId,
  type PlotInput,
  type PlotListQuery,
  type PlotRecord,
  type PlotUpdateInput,
} from '@agrisense/shared';
